add_test([=[FrameTest.UdpFrame]=]  C:/Users/socce/OneDrive/Desktop/OMI/hpcap/build/Debug/frame_tests.exe [==[--gtest_filter=FrameTest.UdpFrame]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FrameTest.UdpFrame]=]  PROPERTIES WORKING_DIRECTORY C:/Users/socce/OneDrive/Desktop/OMI/hpcap/build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FrameTest.VlanTcpFrame]=]  C:/Users/socce/OneDrive/Desktop/OMI/hpcap/build/Debug/frame_tests.exe [==[--gtest_filter=FrameTest.VlanTcpFrame]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FrameTest.VlanTcpFrame]=]  PROPERTIES WORKING_DIRECTORY C:/Users/socce/OneDrive/Desktop/OMI/hpcap/build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FrameTest.TruncatedFrame]=]  C:/Users/socce/OneDrive/Desktop/OMI/hpcap/build/Debug/frame_tests.exe [==[--gtest_filter=FrameTest.TruncatedFrame]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FrameTest.TruncatedFrame]=]  PROPERTIES WORKING_DIRECTORY C:/Users/socce/OneDrive/Desktop/OMI/hpcap/build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FrameTest.NonIpv4Frame]=]  C:/Users/socce/OneDrive/Desktop/OMI/hpcap/build/Debug/frame_tests.exe [==[--gtest_filter=FrameTest.NonIpv4Frame]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FrameTest.NonIpv4Frame]=]  PROPERTIES WORKING_DIRECTORY C:/Users/socce/OneDrive/Desktop/OMI/hpcap/build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FrameTest.TruncatedUdpHeader]=]  C:/Users/socce/OneDrive/Desktop/OMI/hpcap/build/Debug/frame_tests.exe [==[--gtest_filter=FrameTest.TruncatedUdpHeader]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FrameTest.TruncatedUdpHeader]=]  PROPERTIES WORKING_DIRECTORY C:/Users/socce/OneDrive/Desktop/OMI/hpcap/build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FrameTest.NonUdpTcpIpv4Frame]=]  C:/Users/socce/OneDrive/Desktop/OMI/hpcap/build/Debug/frame_tests.exe [==[--gtest_filter=FrameTest.NonUdpTcpIpv4Frame]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FrameTest.NonUdpTcpIpv4Frame]=]  PROPERTIES WORKING_DIRECTORY C:/Users/socce/OneDrive/Desktop/OMI/hpcap/build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  frame_tests_TESTS FrameTest.UdpFrame FrameTest.VlanTcpFrame FrameTest.TruncatedFrame FrameTest.NonIpv4Frame FrameTest.TruncatedUdpHeader FrameTest.NonUdpTcpIpv4Frame)
