if(EXISTS "C:/Users/socce/Desktop/OMI/hpcap/build-check/frame_tests[1]_tests.cmake")
  include("C:/Users/socce/Desktop/OMI/hpcap/build-check/frame_tests[1]_tests.cmake")
else()
  add_test(frame_tests_NOT_BUILT frame_tests_NOT_BUILT)
endif()
